package Controllers.Consultation;

import entities.Consultation;
import entities.Notification;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.stage.Stage;
import services.ServiceConsultation;
import services.ServiceNotification;

import java.io.IOException;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class UpcomingConsultationChecker {
    private final ServiceConsultation serviceConsultation;
    private final ServiceNotification serviceNotification;
    private final List<Notification> notifications;

    public UpcomingConsultationChecker(ServiceConsultation serviceConsultation, ServiceNotification serviceNotification) {
        this.serviceConsultation = serviceConsultation;
        this.serviceNotification = serviceNotification;
        this.notifications = new ArrayList<>();
    }

    public void checkUpcomingConsultations() {
        try {
            List<Consultation> upcomingConsultations = serviceConsultation.getUpcomingConsultations();
            if (!upcomingConsultations.isEmpty()) {
                System.out.println("found upcoming consultations");
                for (Consultation consultation : upcomingConsultations) {
                    LocalDateTime now = LocalDateTime.now();
                    LocalDateTime consultationDateTime = consultation.getDateC();
                    if (now.plusHours(24).isAfter(consultationDateTime)) {
                        createNotification(consultation);
                    }
                }
            //showAlert(upcomingConsultations);
                FXMLLoader loader = new FXMLLoader(getClass().getResource("/Front/Consultation/popup.fxml"));
                Parent root = loader.load();
               // EditConsultationDoctor controller = loader.getController();
               // controller.setConsultation(this.currentConsultation);
                //  MainFX.setCenterView(root);
                Stage stage = new Stage();
                stage.setScene(new Scene(root));
                stage.show();
            } else {
                System.out.println("No upcoming consultations found.");
            }
        } catch (SQLException e) {
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    private void createNotification(Consultation consultation) {
        Notification notification = new Notification(
                0, // The ID will be auto-generated by the database
                consultation.getIdp(),
                "Upcoming Consultation",
                "Consultation for patient " + consultation.getIdp() + " on " + consultation.getDateC(),
                LocalDateTime.now(),
                false
        );

        try {
            serviceNotification.ajouter(notification);
            notifications.add(notification);
        } catch (SQLException e) {
        }
    }

    private void showAlert(List<Consultation> upcomingConsultations) {
        Alert alert = new Alert(Alert.AlertType.INFORMATION);
        alert.setTitle("Upcoming Consultations");
        alert.setHeaderText("You have upcoming consultations in less than 24 hours:");
        StringBuilder message = new StringBuilder();
        for (Consultation consultation : upcomingConsultations) {
            message.append(consultation.toString()).append("\n");
        }
        alert.setContentText(message.toString());
        alert.showAndWait();
    }

    public List<Notification> getNotifications() {
        return notifications;
    }
}